version: "3"

services:
  mysqldb:
   container_name: mysql12456
   image: mysql:8
   restart: unless-stopped
   ports:
    - 3307:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: mohamedbenmiled/achat2345 
   container_name: achat2345
   restart: unless-stopped
   ports:
    - 8082:8082
   depends_on:
    - mysqldb
